var tweets =
[
  { metadata:
  { iso_language_code: 'en', result_type: 'recent' },
  created_at: 'Sun Mar 13 14:42:57 +0000 2016',
    id: 709026968424030200,
  id_str: '709026968424030210',
  text: '2 re-sign or not 2 re-sign #RyanFitzpatrick. Everyone asks that question eventually https://t.co/bsme3399LY #Jets https://t.co/HDv9RJuVDy',
  source: '<a href="https://medium.com" rel="nofollow">Medium</a>',
  truncated: false,
  in_reply_to_status_id: null,
  in_reply_to_status_id_str: null,
  in_reply_to_user_id: null,
  in_reply_to_user_id_str: null,
  in_reply_to_screen_name: null,
  user:
  { id: 59653104,
    id_str: '59653104',
    name: 'julian rogers',
    screen_name: 'thejujueye',
    location: 'Pacific coast',
    description: 'Writer, editor, Web publisher, other. Part man, part coffee. Sub-optimal towel folder.',
    url: 'http://t.co/wTku8yTXaP',
    entities: [Object],
    protected: false,
    followers_count: 1681,
    friends_count: 1982,
    listed_count: 39,
    created_at: 'Fri Jul 24 01:35:46 +0000 2009',
    favourites_count: 3840,
    utc_offset: -25200,
    time_zone: 'Pacific Time (US & Canada)',
    geo_enabled: true,
    verified: false,
    statuses_count: 4715,
    lang: 'en',
    contributors_enabled: false,
    is_translator: false,
    is_translation_enabled: false,
    profile_background_color: '131516',
    profile_background_image_url: 'http://abs.twimg.com/images/themes/theme14/bg.gif',
    profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme14/bg.gif',
    profile_background_tile: true,
    profile_image_url: 'http://pbs.twimg.com/profile_images/439119649146277888/Ob9N39hX_normal.jpeg',
    profile_image_url_https: 'https://pbs.twimg.com/profile_images/439119649146277888/Ob9N39hX_normal.jpeg',
    profile_banner_url: 'https://pbs.twimg.com/profile_banners/59653104/1398441657',
    profile_link_color: '009999',
    profile_sidebar_border_color: 'EEEEEE',
    profile_sidebar_fill_color: 'EFEFEF',
    profile_text_color: '333333',
    profile_use_background_image: true,
    has_extended_profile: false,
    default_profile: false,
    default_profile_image: false,
    following: false,
    follow_request_sent: false,
    notifications: false },
  geo: null,
    coordinates: null,
  place: null,
  contributors: null,
  is_quote_status: false,
  retweet_count: 0,
  favorite_count: 0,
  entities:
  { hashtags: [Object],
    symbols: [],
    user_mentions: [],
    urls: [Object],
    media: [Object] },
  favorited: false,
    retweeted: false,
  possibly_sensitive: false,
  lang: 'en' },
{ metadata: { iso_language_code: 'en', result_type: 'recent' },
  created_at: 'Sun Mar 13 14:06:29 +0000 2016',
    id: 709017793073692700,
  id_str: '709017793073692673',
  text: 'I\'m hiring for a Node.JS/React Developer. Know someone great? in Scottsdale, AZ https://t.co/DlhYn3sRuU #job',
  source: '<a href="http://www.bullhornreach.com/" rel="nofollow">Bullhorn Reach</a>',
  truncated: false,
  in_reply_to_status_id: null,
  in_reply_to_status_id_str: null,
  in_reply_to_user_id: null,
  in_reply_to_user_id_str: null,
  in_reply_to_screen_name: null,
  user:
  { id: 407856042,
    id_str: '407856042',
    name: 'Rob Jones',
    screen_name: 'RAllenJones',
    location: 'Arizona',
    description: 'Recruiting local IT Talent for Contract, contract to hire and Direct hire jobs.',
    url: 'http://t.co/ghjaqYFyZZ',
    entities: [Object],
    protected: false,
    followers_count: 27,
    friends_count: 55,
    listed_count: 6,
    created_at: 'Tue Nov 08 17:03:38 +0000 2011',
    favourites_count: 4,
    utc_offset: null,
    time_zone: null,
    geo_enabled: false,
    verified: false,
    statuses_count: 5180,
    lang: 'en',
    contributors_enabled: false,
    is_translator: false,
    is_translation_enabled: false,
    profile_background_color: 'C0DEED',
    profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
    profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
    profile_background_tile: false,
    profile_image_url: 'http://abs.twimg.com/sticky/default_profile_images/default_profile_6_normal.png',
    profile_image_url_https: 'https://abs.twimg.com/sticky/default_profile_images/default_profile_6_normal.png',
    profile_link_color: '0084B4',
    profile_sidebar_border_color: 'C0DEED',
    profile_sidebar_fill_color: 'DDEEF6',
    profile_text_color: '333333',
    profile_use_background_image: true,
    has_extended_profile: false,
    default_profile: true,
    default_profile_image: true,
    following: false,
    follow_request_sent: false,
    notifications: false },
  geo: null,
    coordinates: null,
  place: null,
  contributors: null,
  is_quote_status: false,
  retweet_count: 0,
  favorite_count: 0,
  entities:
  { hashtags: [Object],
    symbols: [],
    user_mentions: [],
    urls: [Object] },
  favorited: false,
    retweeted: false,
  possibly_sensitive: false,
  lang: 'en' },
{ metadata: { iso_language_code: 'en', result_type: 'recent' },
  created_at: 'Sun Mar 13 13:28:40 +0000 2016',
    id: 709008277984694300,
  id_str: '709008277984694272',
  text: '@AwesomeKermit @AnnCoulter @Noin007 on average I guess I called them stupid, sure, but you need to learn to read instead of looking to react',
  source: '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
  truncated: false,
  in_reply_to_status_id: 708851654427185200,
  in_reply_to_status_id_str: '708851654427185153',
  in_reply_to_user_id: 2799282698,
  in_reply_to_user_id_str: '2799282698',
  in_reply_to_screen_name: 'AwesomeKermit',
  user:
  { id: 2920051736,
    id_str: '2920051736',
    name: 'Cat in the Tower',
    screen_name: 'Minagica',
    location: '',
    description: 'I like facts, reason, empathy and self-improvement. I\'m an indiscriminate RTer of otter pics. Living under a rock on the internet. Waifu of @CaffComm',
    url: null,
    entities: [Object],
    protected: false,
    followers_count: 389,
    friends_count: 499,
    listed_count: 21,
    created_at: 'Fri Dec 05 23:59:49 +0000 2014',
    favourites_count: 7097,
    utc_offset: null,
    time_zone: null,
    geo_enabled: false,
    verified: false,
    statuses_count: 11101,
    lang: 'en',
    contributors_enabled: false,
    is_translator: false,
    is_translation_enabled: false,
    profile_background_color: '000000',
    profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
    profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
    profile_background_tile: false,
    profile_image_url: 'http://pbs.twimg.com/profile_images/650492224745160704/JYeL3bVK_normal.jpg',
    profile_image_url_https: 'https://pbs.twimg.com/profile_images/650492224745160704/JYeL3bVK_normal.jpg',
    profile_banner_url: 'https://pbs.twimg.com/profile_banners/2920051736/1451637937',
    profile_link_color: '9266CC',
    profile_sidebar_border_color: '000000',
    profile_sidebar_fill_color: '000000',
    profile_text_color: '000000',
    profile_use_background_image: false,
    has_extended_profile: false,
    default_profile: false,
    default_profile_image: false,
    following: false,
    follow_request_sent: false,
    notifications: false },
  geo: null,
    coordinates: null,
  place: null,
  contributors: null,
  is_quote_status: false,
  retweet_count: 0,
  favorite_count: 0,
  entities: { hashtags: [], symbols: [], user_mentions: [Object], urls: [] },
  favorited: false,
    retweeted: false,
  lang: 'en' },
{ metadata: { iso_language_code: 'en', result_type: 'recent' },
  created_at: 'Sun Mar 13 13:17:38 +0000 2016',
    id: 709005501254803500,
  id_str: '709005501254803457',
  text: '@IanWright0 How will you react if Spurs win the BPL? As it\'s looking like a very real possibility #AskWrighty',
  source: '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
  truncated: false,
  in_reply_to_status_id: null,
  in_reply_to_status_id_str: null,
  in_reply_to_user_id: 410811457,
  in_reply_to_user_id_str: '410811457',
  in_reply_to_screen_name: 'IanWright0',
  user:
  { id: 499329143,
    id_str: '499329143',
    name: 'Ste Bingham',
    screen_name: 'SteBingham',
    location: 'Yorkshire, Derby, W Brom, UK',
    description: 'Tweet, Teach, Sleep, Repeat.',
    url: null,
    entities: [Object],
    protected: false,
    followers_count: 114,
    friends_count: 303,
    listed_count: 0,
    created_at: 'Wed Feb 22 00:57:33 +0000 2012',
    favourites_count: 87,
    utc_offset: 0,
    time_zone: 'London',
    geo_enabled: true,
    verified: false,
    statuses_count: 1541,
    lang: 'en',
    contributors_enabled: false,
    is_translator: false,
    is_translation_enabled: false,
    profile_background_color: '000000',
    profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
    profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
    profile_background_tile: false,
    profile_image_url: 'http://pbs.twimg.com/profile_images/688487028443447296/OnIIrgym_normal.jpg',
    profile_image_url_https: 'https://pbs.twimg.com/profile_images/688487028443447296/OnIIrgym_normal.jpg',
    profile_banner_url: 'https://pbs.twimg.com/profile_banners/499329143/1452983623',
    profile_link_color: '4A913C',
    profile_sidebar_border_color: '000000',
    profile_sidebar_fill_color: '000000',
    profile_text_color: '000000',
    profile_use_background_image: false,
    has_extended_profile: true,
    default_profile: false,
    default_profile_image: false,
    following: false,
    follow_request_sent: false,
    notifications: false },
  geo: null,
    coordinates: null,
  place: null,
  contributors: null,
  is_quote_status: false,
  retweet_count: 0,
  favorite_count: 0,
  entities:
  { hashtags: [Object],
    symbols: [],
    user_mentions: [Object],
    urls: [] },
  favorited: false,
    retweeted: false,
  lang: 'en' },
{ metadata: { iso_language_code: 'en', result_type: 'recent' },
  created_at: 'Sun Mar 13 11:55:24 +0000 2016',
    id: 708984805782896600,
  id_str: '708984805782896641',
  text: 'Apply to this job: Senior Presentation Layer Developer - (React.js) in New York, NY https://t.co/In0mLkckGo #job',
  source: '<a href="http://www.bullhornreach.com/" rel="nofollow">Bullhorn Reach</a>',
  truncated: false,
  in_reply_to_status_id: null,
  in_reply_to_status_id_str: null,
  in_reply_to_user_id: null,
  in_reply_to_user_id_str: null,
  in_reply_to_screen_name: null,
  user:
  { id: 716243994,
    id_str: '716243994',
    name: 'Next Step Staffing',
    screen_name: 'NextStepStaff',
    location: 'Flatiron District NYC',
    description: 'Technology Placement firm in NYC - Keeping you up to date with the newest technology focused roles',
    url: 'http://t.co/qQQ0DGlhUf',
    entities: [Object],
    protected: false,
    followers_count: 146,
    friends_count: 162,
    listed_count: 58,
    created_at: 'Wed Jul 25 15:21:40 +0000 2012',
    favourites_count: 3,
    utc_offset: -14400,
    time_zone: 'Eastern Time (US & Canada)',
    geo_enabled: false,
    verified: false,
    statuses_count: 4557,
    lang: 'en',
    contributors_enabled: false,
    is_translator: false,
    is_translation_enabled: false,
    profile_background_color: '292A2B',
    profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/635994621/4eqwwz61dw4td4bjgpga.png',
    profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/635994621/4eqwwz61dw4td4bjgpga.png',
    profile_background_tile: true,
    profile_image_url: 'http://pbs.twimg.com/profile_images/2515734314/98lm9gjsct4e28hkshzu_normal.png',
    profile_image_url_https: 'https://pbs.twimg.com/profile_images/2515734314/98lm9gjsct4e28hkshzu_normal.png',
    profile_banner_url: 'https://pbs.twimg.com/profile_banners/716243994/1413502170',
    profile_link_color: '4A913C',
    profile_sidebar_border_color: 'C0DEED',
    profile_sidebar_fill_color: 'DDEEF6',
    profile_text_color: '333333',
    profile_use_background_image: true,
    has_extended_profile: false,
    default_profile: false,
    default_profile_image: false,
    following: false,
    follow_request_sent: false,
    notifications: false },
  geo: null,
    coordinates: null,
  place: null,
  contributors: null,
  is_quote_status: false,
  retweet_count: 0,
  favorite_count: 0,
  entities:
  { hashtags: [Object],
    symbols: [],
    user_mentions: [],
    urls: [Object] },
  favorited: false,
    retweeted: false,
  possibly_sensitive: false,
  lang: 'en' },
{ metadata: { iso_language_code: 'en', result_type: 'recent' },
  created_at: 'Sun Mar 13 11:29:57 +0000 2016',
    id: 708978399985803300,
  id_str: '708978399985803265',
  text: '#NFL #Bears Pat Fitzgerald, Gerry DiNardo react to Lovie Smith\'s hiring at Illinois https://t.co/eBthCrwBIw https://t.co/5X86huggCr',
  source: '<a href="http://sportsfanzone.org" rel="nofollow">Bears Fan Zone</a>',
  truncated: false,
  in_reply_to_status_id: null,
  in_reply_to_status_id_str: null,
  in_reply_to_user_id: null,
  in_reply_to_user_id_str: null,
  in_reply_to_screen_name: null,
  user:
  { id: 538377230,
    id_str: '538377230',
    name: 'Bears Fan Zone',
    screen_name: 'Bears_FZ',
    location: 'Chicago',
    description: 'Welcome to the Chicago Bears Fan Zone. Where we talk Bears football all day, every day. Follow now if you\'re a Bears fanatic!',
    url: 'https://t.co/opDX9r6pC9',
    entities: [Object],
    protected: false,
    followers_count: 1380,
    friends_count: 680,
    listed_count: 48,
    created_at: 'Tue Mar 27 18:20:24 +0000 2012',
    favourites_count: 209,
    utc_offset: -18000,
    time_zone: 'Central Time (US & Canada)',
    geo_enabled: false,
    verified: false,
    statuses_count: 8927,
    lang: 'en',
    contributors_enabled: false,
    is_translator: false,
    is_translation_enabled: false,
    profile_background_color: '131516',
    profile_background_image_url: 'http://abs.twimg.com/images/themes/theme14/bg.gif',
    profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme14/bg.gif',
    profile_background_tile: true,
    profile_image_url: 'http://pbs.twimg.com/profile_images/553226515530268673/n881P8PO_normal.png',
    profile_image_url_https: 'https://pbs.twimg.com/profile_images/553226515530268673/n881P8PO_normal.png',
    profile_banner_url: 'https://pbs.twimg.com/profile_banners/538377230/1419698492',
    profile_link_color: '3B94D9',
    profile_sidebar_border_color: '829D5E',
    profile_sidebar_fill_color: '99CC33',
    profile_text_color: '3E4415',
    profile_use_background_image: true,
    has_extended_profile: false,
    default_profile: false,
    default_profile_image: false,
    following: false,
    follow_request_sent: false,
    notifications: false },
  geo: null,
    coordinates: null,
  place: null,
  contributors: null,
  is_quote_status: false,
  retweet_count: 0,
  favorite_count: 0,
  entities:
  { hashtags: [Object],
    symbols: [],
    user_mentions: [],
    urls: [Object],
    media: [Object] },
  favorited: false,
    retweeted: false,
  possibly_sensitive: false,
  lang: 'en' },
{ metadata: { iso_language_code: 'en', result_type: 'recent' },
  created_at: 'Sun Mar 13 11:16:11 +0000 2016',
    id: 708974937944498200,
  id_str: '708974937944498180',
  text: 'Job Opportunity! Sr. Software Engineer in Detroit, MI https://t.co/W3h5qMJXdA #job #react.js',
  source: '<a href="http://www.bullhornreach.com/" rel="nofollow">Bullhorn Reach</a>',
  truncated: false,
  in_reply_to_status_id: null,
  in_reply_to_status_id_str: null,
  in_reply_to_user_id: null,
  in_reply_to_user_id_str: null,
  in_reply_to_screen_name: null,
  user:
  { id: 256529964,
    id_str: '256529964',
    name: 'grep staff llc',
    screen_name: 'grepstaff',
    location: 'Smyrna, Georgia',
    description: 'grep [grep] verb, 1) to search for something by pattern... Atlanta Georgia based IT staffing organization founded by a Software Engineer and Recruiter',
    url: 'http://t.co/vi4Vbf1Phk',
    entities: [Object],
    protected: false,
    followers_count: 179,
    friends_count: 352,
    listed_count: 23,
    created_at: 'Wed Feb 23 14:43:21 +0000 2011',
    favourites_count: 3,
    utc_offset: -18000,
    time_zone: 'Quito',
    geo_enabled: true,
    verified: false,
    statuses_count: 3237,
    lang: 'en',
    contributors_enabled: false,
    is_translator: false,
    is_translation_enabled: false,
    profile_background_color: '0A0A0A',
    profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/863678687/c4c1833f058d58e19776b336257e10f5.png',
    profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/863678687/c4c1833f058d58e19776b336257e10f5.png',
    profile_background_tile: false,
    profile_image_url: 'http://pbs.twimg.com/profile_images/672500190390059008/jg4L5gZ8_normal.png',
    profile_image_url_https: 'https://pbs.twimg.com/profile_images/672500190390059008/jg4L5gZ8_normal.png',
    profile_banner_url: 'https://pbs.twimg.com/profile_banners/256529964/1449171101',
    profile_link_color: '080808',
    profile_sidebar_border_color: 'FFFFFF',
    profile_sidebar_fill_color: 'C0DFEC',
    profile_text_color: '333333',
    profile_use_background_image: true,
    has_extended_profile: false,
    default_profile: false,
    default_profile_image: false,
    following: false,
    follow_request_sent: false,
    notifications: false },
  geo: null,
    coordinates: null,
  place: null,
  contributors: null,
  is_quote_status: false,
  retweet_count: 0,
  favorite_count: 0,
  entities:
  { hashtags: [Object],
    symbols: [],
    user_mentions: [],
    urls: [Object] },
  favorited: false,
    retweeted: false,
  possibly_sensitive: false,
  lang: 'en' },
{ metadata: { iso_language_code: 'en', result_type: 'recent' },
  created_at: 'Sun Mar 13 10:10:12 +0000 2016',
    id: 708958329603752000,
  id_str: '708958329603751937',
  text: 'One Week...3 different competitions Watford Home Barça and Everton Away Looking farward to see how the team gonna react Come on you #Arsenal',
  source: '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
  truncated: false,
  in_reply_to_status_id: null,
  in_reply_to_status_id_str: null,
  in_reply_to_user_id: null,
  in_reply_to_user_id_str: null,
  in_reply_to_screen_name: null,
  user:
  { id: 796863151,
    id_str: '796863151',
    name: 'Mr.MaGnificent',
    screen_name: 'DCalimero',
    location: 'Nigga...i Hit\'em Up ',
    description: 'Happiness Depends on @Arsenal .',
    url: null,
    entities: [Object],
    protected: false,
    followers_count: 1331,
    friends_count: 1540,
    listed_count: 13,
    created_at: 'Sat Sep 01 20:55:22 +0000 2012',
    favourites_count: 2438,
    utc_offset: 3600,
    time_zone: 'Paris',
    geo_enabled: true,
    verified: false,
    statuses_count: 5255,
    lang: 'en-gb',
    contributors_enabled: false,
    is_translator: false,
    is_translation_enabled: false,
    profile_background_color: '1A1B1F',
    profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/378800000179993577/ObU4b0vv.jpeg',
    profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/378800000179993577/ObU4b0vv.jpeg',
    profile_background_tile: true,
    profile_image_url: 'http://pbs.twimg.com/profile_images/707913481354387456/AAg5XaYw_normal.jpg',
    profile_image_url_https: 'https://pbs.twimg.com/profile_images/707913481354387456/AAg5XaYw_normal.jpg',
    profile_banner_url: 'https://pbs.twimg.com/profile_banners/796863151/1446307222',
    profile_link_color: '2FC2EF',
    profile_sidebar_border_color: 'FFFFFF',
    profile_sidebar_fill_color: '252429',
    profile_text_color: '666666',
    profile_use_background_image: true,
    has_extended_profile: false,
    default_profile: false,
    default_profile_image: false,
    following: false,
    follow_request_sent: false,
    notifications: false },
  geo: null,
    coordinates: null,
  place: null,
  contributors: null,
  is_quote_status: false,
  retweet_count: 0,
  favorite_count: 0,
  entities: { hashtags: [Object], symbols: [], user_mentions: [], urls: [] },
  favorited: false,
    retweeted: false,
  lang: 'en' },
{ metadata: { iso_language_code: 'en', result_type: 'recent' },
  created_at: 'Sun Mar 13 08:04:40 +0000 2016',
    id: 708926741121617900,
  id_str: '708926741121617920',
  text: '#Job #Georgia (USA-GA-Atlanta) Front End Engineer - JavaScript, React and Node: As a Front End Engineer, you\'l... https://t.co/dBhMkJ5DJn',
  source: '<a href="http://twitterfeed.com" rel="nofollow">twitterfeed</a>',
  truncated: false,
  in_reply_to_status_id: null,
  in_reply_to_status_id_str: null,
  in_reply_to_user_id: null,
  in_reply_to_user_id_str: null,
  in_reply_to_screen_name: null,
  user:
  { id: 2361072098,
    id_str: '2361072098',
    name: 'Jobs in Georgia',
    screen_name: 'Jobs_Georgia',
    location: 'Georgia',
    description: 'Tweets with latest #Jobs #Offers in #Georgia !!',
    url: null,
    entities: [Object],
    protected: false,
    followers_count: 488,
    friends_count: 593,
    listed_count: 117,
    created_at: 'Tue Feb 25 13:17:20 +0000 2014',
    favourites_count: 0,
    utc_offset: 3600,
    time_zone: 'Amsterdam',
    geo_enabled: false,
    verified: false,
    statuses_count: 235410,
    lang: 'en',
    contributors_enabled: false,
    is_translator: false,
    is_translation_enabled: false,
    profile_background_color: 'C0DEED',
    profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
    profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
    profile_background_tile: false,
    profile_image_url: 'http://pbs.twimg.com/profile_images/438301921380556800/USotaEH9_normal.jpeg',
    profile_image_url_https: 'https://pbs.twimg.com/profile_images/438301921380556800/USotaEH9_normal.jpeg',
    profile_link_color: '0084B4',
    profile_sidebar_border_color: 'C0DEED',
    profile_sidebar_fill_color: 'DDEEF6',
    profile_text_color: '333333',
    profile_use_background_image: true,
    has_extended_profile: false,
    default_profile: true,
    default_profile_image: false,
    following: false,
    follow_request_sent: false,
    notifications: false },
  geo: null,
    coordinates: null,
  place: null,
  contributors: null,
  is_quote_status: false,
  retweet_count: 0,
  favorite_count: 2,
  entities:
  { hashtags: [Object],
    symbols: [],
    user_mentions: [],
    urls: [Object] },
  favorited: false,
    retweeted: false,
  possibly_sensitive: false,
  lang: 'en' },
{ metadata: { iso_language_code: 'en', result_type: 'recent' },
  created_at: 'Sun Mar 13 07:53:46 +0000 2016',
    id: 708923995324870700,
  id_str: '708923995324870656',
  text: '@FeistyKirkland He was a bit afraid on how she would react, soon stopping in his tracks and slowly looking over at her. "W-What is it?"',
  source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
  truncated: false,
  in_reply_to_status_id: 708923183223722000,
  in_reply_to_status_id_str: '708923183223721984',
  in_reply_to_user_id: 704285172393492500,
  in_reply_to_user_id_str: '704285172393492483',
  in_reply_to_screen_name: 'FeistyKirkland',
  user:
  { id: 3376149695,
    id_str: '3376149695',
    name: 'Gogeta [ゴジータ]',
    screen_name: 'xFusionLove',
    location: '',
    description: 'I am neither Goku or Vegeta, fear me, for I am the man who shall defeat you! Potara fusion counterpart: @xFusionLust [#MVRP R-21+ RP]',
    url: null,
    entities: [Object],
    protected: false,
    followers_count: 159,
    friends_count: 131,
    listed_count: 0,
    created_at: 'Tue Jul 14 18:17:28 +0000 2015',
    favourites_count: 9,
    utc_offset: null,
    time_zone: null,
    geo_enabled: true,
    verified: false,
    statuses_count: 71,
    lang: 'en',
    contributors_enabled: false,
    is_translator: false,
    is_translation_enabled: false,
    profile_background_color: 'C0DEED',
    profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
    profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
    profile_background_tile: false,
    profile_image_url: 'http://pbs.twimg.com/profile_images/703678264645181440/S5DTh6sz_normal.jpg',
    profile_image_url_https: 'https://pbs.twimg.com/profile_images/703678264645181440/S5DTh6sz_normal.jpg',
    profile_banner_url: 'https://pbs.twimg.com/profile_banners/3376149695/1456604946',
    profile_link_color: '0084B4',
    profile_sidebar_border_color: 'C0DEED',
    profile_sidebar_fill_color: 'DDEEF6',
    profile_text_color: '333333',
    profile_use_background_image: true,
    has_extended_profile: false,
    default_profile: true,
    default_profile_image: false,
    following: false,
    follow_request_sent: false,
    notifications: false },
  geo: null,
    coordinates: null,
  place: null,
  contributors: null,
  is_quote_status: false,
  retweet_count: 0,
  favorite_count: 0,
  entities: { hashtags: [], symbols: [], user_mentions: [Object], urls: [] },
  favorited: false,
    retweeted: false,
  lang: 'en' },
{ metadata: { iso_language_code: 'en', result_type: 'recent' },
  created_at: 'Sun Mar 13 07:17:17 +0000 2016',
    id: 708914813548691500,
  id_str: '708914813548691456',
  text: 'The other day I walked past a 7th grader and he said to me "you\'re hot, good job." I didn\'t know how to react so I said "um, thanks."',
  source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
  truncated: false,
  in_reply_to_status_id: null,
  in_reply_to_status_id_str: null,
  in_reply_to_user_id: null,
  in_reply_to_user_id_str: null,
  in_reply_to_screen_name: null,
  user:
  { id: 549628822,
    id_str: '549628822',
    name: 'lauren',
    screen_name: 'punkxmuke',
    location: '5/4 ',
    description: 'Fear might be the death of me. Fear leads to anxiety.',
    url: null,
    entities: [Object],
    protected: false,
    followers_count: 27602,
    friends_count: 18823,
    listed_count: 191,
    created_at: 'Mon Apr 09 23:19:39 +0000 2012',
    favourites_count: 7220,
    utc_offset: 36000,
    time_zone: 'Brisbane',
    geo_enabled: true,
    verified: false,
    statuses_count: 94770,
    lang: 'en',
    contributors_enabled: false,
    is_translator: false,
    is_translation_enabled: false,
    profile_background_color: 'FFFFFF',
    profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/378800000161492676/FaBuIofQ.jpeg',
    profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/378800000161492676/FaBuIofQ.jpeg',
    profile_background_tile: true,
    profile_image_url: 'http://pbs.twimg.com/profile_images/708996208144953344/IDCV7W_c_normal.jpg',
    profile_image_url_https: 'https://pbs.twimg.com/profile_images/708996208144953344/IDCV7W_c_normal.jpg',
    profile_banner_url: 'https://pbs.twimg.com/profile_banners/549628822/1457872769',
    profile_link_color: '099146',
    profile_sidebar_border_color: '000000',
    profile_sidebar_fill_color: 'DDEEF6',
    profile_text_color: '333333',
    profile_use_background_image: true,
    has_extended_profile: true,
    default_profile: false,
    default_profile_image: false,
    following: false,
    follow_request_sent: false,
    notifications: false },
  geo: null,
    coordinates: null,
  place: null,
  contributors: null,
  is_quote_status: false,
  retweet_count: 0,
  favorite_count: 1,
  entities: { hashtags: [], symbols: [], user_mentions: [], urls: [] },
  favorited: false,
    retweeted: false,
  lang: 'en' },
{ metadata: { iso_language_code: 'en', result_type: 'recent' },
  created_at: 'Sun Mar 13 05:35:29 +0000 2016',
    id: 708889195956166700,
  id_str: '708889195956166658',
  text: 'RT @DiscoverRedwolf: Redwolf is hiring! UI #Developer (#AngularJS / #React.js) Melbourne #startup, small, #agile team. Great culture. Get i…',
  source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
  truncated: false,
  in_reply_to_status_id: null,
  in_reply_to_status_id_str: null,
  in_reply_to_user_id: null,
  in_reply_to_user_id_str: null,
  in_reply_to_screen_name: null,
  user:
  { id: 2882590232,
    id_str: '2882590232',
    name: 'Thomas Sparks',
    screen_name: 'SparksThom',
    location: 'Melbourne, Australia',
    description: 'Accounting Extraordinaire, Tech Enthusiast, Business Nerd, Latte Drinker & Mandarin Beginner',
    url: 'https://t.co/StGa3S5YH1',
    entities: [Object],
    protected: false,
    followers_count: 133,
    friends_count: 309,
    listed_count: 14,
    created_at: 'Wed Oct 29 21:42:21 +0000 2014',
    favourites_count: 226,
    utc_offset: null,
    time_zone: null,
    geo_enabled: false,
    verified: false,
    statuses_count: 116,
    lang: 'en-AU',
    contributors_enabled: false,
    is_translator: false,
    is_translation_enabled: false,
    profile_background_color: 'C0DEED',
    profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
    profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
    profile_background_tile: false,
    profile_image_url: 'http://pbs.twimg.com/profile_images/701314292478423040/eSUFzIqq_normal.jpg',
    profile_image_url_https: 'https://pbs.twimg.com/profile_images/701314292478423040/eSUFzIqq_normal.jpg',
    profile_banner_url: 'https://pbs.twimg.com/profile_banners/2882590232/1456041332',
    profile_link_color: '0084B4',
    profile_sidebar_border_color: 'C0DEED',
    profile_sidebar_fill_color: 'DDEEF6',
    profile_text_color: '333333',
    profile_use_background_image: true,
    has_extended_profile: false,
    default_profile: true,
    default_profile_image: false,
    following: false,
    follow_request_sent: false,
    notifications: false },
  geo: null,
    coordinates: null,
  place: null,
  contributors: null,
  retweeted_status:
  { metadata: [Object],
    created_at: 'Mon Feb 29 11:28:03 +0000 2016',
    id: 704266881100869600,
    id_str: '704266881100869632',
    text: 'Redwolf is hiring! UI #Developer (#AngularJS / #React.js) Melbourne #startup, small, #agile team. Great culture. Get in touch for info!',
    source: '<a href="http://bufferapp.com" rel="nofollow">Buffer</a>',
    truncated: false,
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: [Object],
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 1,
    favorite_count: 6,
    entities: [Object],
    favorited: false,
    retweeted: false,
    lang: 'en' },
  is_quote_status: false,
    retweet_count: 1,
  favorite_count: 0,
  entities:
  { hashtags: [Object],
    symbols: [],
    user_mentions: [Object],
    urls: [] },
  favorited: false,
    retweeted: false,
  lang: 'en' },
{ metadata: { iso_language_code: 'en', result_type: 'recent' },
  created_at: 'Sun Mar 13 05:03:21 +0000 2016',
    id: 708881107593404400,
  id_str: '708881107593404416',
  text: 'I know you\'re hoping that I\'ll react\nI know you\'re hoping I\'m looking back',
  source: '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
  truncated: false,
  in_reply_to_status_id: null,
  in_reply_to_status_id_str: null,
  in_reply_to_user_id: null,
  in_reply_to_user_id_str: null,
  in_reply_to_screen_name: null,
  user:
  { id: 1623059635,
    id_str: '1623059635',
    name: 'Jax',
    screen_name: 'michael_mongera',
    location: '',
    description: 'or maybe this is danger and you just don\'t know, You pray it all away but it continues to grow',
    url: null,
    entities: [Object],
    protected: false,
    followers_count: 67,
    friends_count: 322,
    listed_count: 3,
    created_at: 'Fri Jul 26 14:06:57 +0000 2013',
    favourites_count: 515,
    utc_offset: null,
    time_zone: null,
    geo_enabled: false,
    verified: false,
    statuses_count: 1798,
    lang: 'en',
    contributors_enabled: false,
    is_translator: false,
    is_translation_enabled: false,
    profile_background_color: 'C0DEED',
    profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
    profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
    profile_background_tile: false,
    profile_image_url: 'http://pbs.twimg.com/profile_images/694864597203992576/HDYtfNGp_normal.jpg',
    profile_image_url_https: 'https://pbs.twimg.com/profile_images/694864597203992576/HDYtfNGp_normal.jpg',
    profile_banner_url: 'https://pbs.twimg.com/profile_banners/1623059635/1457295601',
    profile_link_color: '0084B4',
    profile_sidebar_border_color: 'C0DEED',
    profile_sidebar_fill_color: 'DDEEF6',
    profile_text_color: '333333',
    profile_use_background_image: true,
    has_extended_profile: false,
    default_profile: true,
    default_profile_image: false,
    following: false,
    follow_request_sent: false,
    notifications: false },
  geo: null,
    coordinates: null,
  place: null,
  contributors: null,
  is_quote_status: false,
  retweet_count: 0,
  favorite_count: 0,
  entities: { hashtags: [], symbols: [], user_mentions: [], urls: [] },
  favorited: false,
    retweeted: false,
  lang: 'en' } ]